@startuml
|ユーザー|
start
:航空便情報を入力;
|チケット予約システム|
:見積り依頼;
|　航空会社システムA　|
fork
  :見積もり;
|　航空会社システムB　|
fork again
  :見積もり;
|　航空会社システムA　|
end fork
:見積もり情報出力;
|チケット予約システム|
:見積もり情報提示;
|ユーザー|
if (予約する?) then (yes)
  :航空会社を指定;
else (no)
  :チケット予約システムに入力;
endif
stop
@enduml