@startuml
left to right direction
skinparam packageStyle rectangle
actor 利用者
rectangle 複合機 {
 利用者  -- (スキャナーで紙を読み込む)
 利用者 -- (スキャナーで読み込んだデータを印刷する)
 利用者 -- (スキャナーで読み込んだデータをUSBに保存する)
 利用者 -- (スキャナーで読み込んだデータをストレージに保存する)
 (スキャナーで読み込んだデータを印刷する).> (スキャナーで紙を読み込む) : include
 (スキャナーで読み込んだデータをUSBに保存する).> (スキャナーで紙を読み込む) : include
 (スキャナーで読み込んだデータをストレージに保存する).> (スキャナーで紙を読み込む) : include
}
@enduml
