@startuml
left to right direction
skinparam packageStyle rectangle
actor 利用者
actor 管理者
rectangle 旅行代理店のWebシステム {
 利用者  -- (旅行を予約する)
 利用者 -- (予約を削除する)
 (予約を削除する).> (予約を変更する) : extend
 利用者 -- (自分の予約を確認する)
 利用者 -- (全体の予約状況を確認する)
 (全体の予約状況を確認する) -- 管理者
 (予約を削除する) -- 管理者
 (予約を変更する) -- 管理者
}
@enduml
